name: Haskell CI

on:
  push:
    branches:
    - "**"
    tags-ignore:
    - "**"
  pull_request:
    branches:
    - "**"
    tags-ignore:
    - "**"
    types:
    - 'opened'
    - 'reopened'
    - 'synchronize'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.2.5'
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build
        run: |
          cabal update
          cabal build --enable-tests --enable-benchmarks all
          cabal install --overwrite-policy=always
      # - run: |
      #     mkdir -p ${{ github.workspace }}/artifact
      #     echo hello > ${{ github.workspace }}/artifact/world.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: haskell-build
          path: /home/runner/work/dhall-terraform/dhall-terraform/dist-newstyle/sdist/
      - name: Run tests
        run: cabal test all
